### ISSUE TITLE
Test for `storefront create --demo`

### ISSUE THREAD

**Issue by lkostrowski** [saleor/devtools-integration-tests#1]
# Context

Command `npx saleor storefront create --demo` is an important starting point for people visiting the Saleor website.

This command must work no matter what, so it's a good candidate for the first "serious" integration test.

# Initial test

GIVEN: 
Saleor CLI is installed (I can set Saleor CLI version in CICD input 💯 )

WHEN:
`npx saleor storefront create --demo` is executed (with other flags non-interactive way)

THEN:
[Repository](https://github.com/saleor/react-storefront) should be created locally
AND
Project should run locally
AND
Any product can be added to basket
AND 
Can proceed to checkout

**Comment by lkostrowski** [comment]
@zaiste can you elaborate on running `npx saleor storefront create --demo` in non-interactive way?

**Comment by zaiste** [comment]
We have now a functional CLI test that covers this scenario and it shows the required argumetns to run this command in the batch (aka non-interactive) mode.

https://github.com/saleor/saleor-cli/blob/main/test/functional/storefront/create.test.ts

There was a change request regarding how `storefront create` works. It doesn't start in development mode. We need to decide how to test the progression from the CLI execution to the browser flow.
