### ISSUE TITLE
Test if `saleor app create` creates app locally

### ISSUE THREAD

**Issue by lkostrowski** [saleor/devtools-integration-tests#2]
Scenario 1 - creation

GIVEN
saleor CLI is installed

WHEN
`saleor app create` is triggered

THEN
app folder is created and files are there

Scenario 2 - dev sever

GIVEN
Scenario 1 is performed
AND
Context is inside app folder

WHEN
`pnpm run dev` is execured

THEN
App should be running on port :3000

**Comment by zaiste** [comment]
https://github.com/saleor/devtools-integration-tests/pull/15

**Comment by zaiste** [comment]
The tests for this scenerio are implemented.
