### ISSUE TITLE
Setup E2E tests CI/CD

### ISSUE THREAD

**Issue by lkostrowski** [saleor/devtools-integration-tests#4]
This repository should have CICD with Github actions running with manual trigger (at the moment).

Via REST API this workflow can be triggered and connected to other repos - like open PR (in Storefront, CLI, Platform, etc), night tests (cron) or before a release.

Failing test should notify on email, slack, etc.

**Comment by michalina-graczyk** [comment]
https://github.com/saleor/devtools-integration-tests/actions/runs/3052254503/workflow I need a help with it.

**Comment by zaiste** [comment]
We changed the underlaying technology from Cypress running CLI commands to Vitest as the latter is much faster and easier to do. Starting today we want to attach a preliminary CI flow to the CLI repository to launch these tests.

**Comment by zaiste** [comment]
Let's prepare a initial document with the **test coverage** for the CLI

**Comment by lkostrowski** [comment]
To finish:
- slack reports 
- dedicated tokens
